---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: {{ .Release.Name }}
  labels: 
    {{- include "cert-manager-letsencrypt-issuer.labels" . | nindent 4 }}
spec:
  acme:
    email: {{ required "ACME email is required" .Values.acme.email | quote }}
    server: {{ required "ACME server is required" .Values.acme.server | quote }}
    privateKeySecretRef:
      name: {{ .Release.Name }}-account-key
    solvers:
    - http01:
        ingress: {}